### PR TITLE
Intermediate refactor 04032024 and transcription feature

### PR DESCRIPTION
**Pull request by vshlemon**
Added the new feature for diarising and transcribing a la Mochan

Have made some more tweaks but still some further work to do on the codebase architecture to solidify it - have made some rough notes in tasks

Should all be working - execute from `modal-transcribe` via. `modal serve backend.main` & also hit the new endpoint via.`api/diarised_transcribe` - there is a Bruno file for it (you may need to change the env-vars & you will need a hugging face key)

### CODE REVIEW

**Comment by sbc** [comment]
@vshlemon Since adding the transcription stuff I'm getting module not found errors trying to run this. It looks like maybe some imports were moved outside of function defs?

**Comment by vshlemon** [comment]
@sbc - would you have the steps to recreate because moving the imports outside the functions doesn't affect the execution from my side. The package installation has been moved from using the `.pip_install` method to using `.poetry_install_from_file` which looks at the dependencies to install from the `backend/poetry.lock` file & I don't think this is looking at my local system to locate packages but is instead looking at online package repositories but I might be mistaken

Did the installation setup go successfully and it is only when triggering the transcription endpoint that you get import errors?

**Comment by sbc** [comment]
I think just create a new python environment and run 

`modal run backend.main`

There are two possible fixes:

1. Provide instructions to create the local environment. I didn't see a requirements file. I guess you're using poetry but I don't know how it works and didn't see an obvious config file beyond the lock file. 

2. Put the imports inside of modal stub functions so they're only executed in the modal container. This is the method mentioned in the modal documentation.

**Comment by vshlemon** [comment]
@sbc - you're probablt right it only works on my machine because of my local setup, I was under the impression that the installs created a virtual environment remotely, seems not. I am trying to replicate your issue to fix it but atm my modal cli is pointed towards a version of python with everything I need installed, I am trying to point it towards a fresh .venv to get it to fail like yours and will then make a new pull request

Apologies for this, I removed any requirements file etc. as I didn't want there to have to be any local setup, should be able to fix it soon once I recreate the issue

Reading the docs recommends that doing:
```
with image.imports():
    import xyz
```
should make everything available in global scope, but I can only verify once I can recreate (you could try though by putting something like the below in `backend/main.py`
```
from backend.ops.image import APP_IMAGE
with APP_IMAGE.imports():
    import pydantic
    import whisper
    import torch
    import pyannote
    ...etc.
```

**Comment by vshlemon** [comment]
You could for the time being create a local env with all you need using poetry, install using the below command

`curl -sSL https://install.python-poetry.org | python3 -`

Then `cd backend` and `poetry install` then `poetry shell` - if it doesn't work because modal can't point towards the poetry env, then you may also need to do `poetry add modal` and then restart the terminal and `poetry shell` within the `backend` dir - it is looking at the `pyproject.toml` file which states all the deps (but they are massive ~5.5GB, so I want to find a way that it just runs remotely only).

**Comment by vshlemon** [comment]
Moving the imports into the stub.functions means you can't separate the 'business-logic' from the modal infrastructure operations, so you couldn't easily try things out locally etc. nor host functionality in appropriately segregated areas

**Comment by sbc** [comment]
I just used my env from the original stt pipeline.

I agree about moving the imports. I like that you've managed to separate out the modal code from the business logic.

**Comment by vshlemon** [comment]
The modal cli seems to 'statically evaluate/lint' the codebase when mounting it, and it does this in the local env. So even though th e code is not being run there and is being called elsewhere eg. how the `PyannoteDiariser` is only actually executed from within the `DiariseAndTranscribeModalOperator` it throws an error.

Unfortunately the solutions are not ideal (can't just add a cli arg to not statically evaluate/lint):

1. Install the same env. as being used remotely on your local machine via. poetry (pip installs created lots of issues with version clashes on the remote machine so had to use a poetry.lock) - you can do this quite easily but the installs are large. `pyproject.toml` is where the dependencies are located (you will also need to do `poetry add modal` to be using a modal cli within the venv), you can install them via. poetry and run modal in the poetry shell. Also if not comfortable with poetry you can convert the file to a `requirements.txt` and install using pip and venv see -(https://github.com/python-poetry/poetry-plugin-export)
2. Refactor the codebase and move all "business logic" inside the modal functionality which I don't like too much as it means you can't cleanly separate functionality and try things out locally etc.
3. I can try a bit more with `with image.imports()` to suppress the errors - I got some advice from the modal support team which I am going to try out - see below


This was modal's response to my queries about why the import errors arise (you can ignore the 1st one, that was an issue of running by global modal install not my poetry one, the 2nd one is re: me using the `image.imports()` but it failing to suppress errors as I didn't have it everywhere it was necessary - this is what I will try fixing):

elias
 [1 hour ago](https://modallabscommunity.slack.com/archives/C069RAH7X4M/p1709712529216619?thread_ts=1709646614.419699&cid=C069RAH7X4M)
Ok so there are two issues afaict here:
1. You probably have/had `modal` installed in your global Python install, rather than the venv (I guess you figured this out since you installed `modal` in the venv above).
2. The reproduced issue with imports that both and your colleague have now, is because not all necessary imports are gated by `image.imports()` (or local to the functions as you mentioned). Since `diariser.py` above also imports pyannote, and `operators.py` imports `diariser`, you have to put the from `backend.ops.diarised_transcribe.operators` within the `image.imports()` block too. Basically any global import that transitively imports a package that isn't locally available should be within such a block to be "safe"

elias
 [1 hour ago](https://modallabscommunity.slack.com/archives/C069RAH7X4M/p1709713023401289?thread_ts=1709646614.419699&cid=C069RAH7X4M)
- To clarify, with `image.imports()` isn't what makes modules available in the container (`poetry_install_from_file()` takes care of that for you), it only make sure that those imports won't break when running locally for you.
- So you don't have to put any unused imports within the block (not sure if you have that), but you do need to put an import block around any global import of modules that you wouldn't be able to import locally. This is because your local Python will traverse all of the imported files in order to interpret all of your Modal configuration before deploying it to the cloud, which it can't do if it breaks on imports.
- Hope this helps. I'd be happy to take a look at the Modal parts o your main python file and give some more pointers if you like - maybe that would clarify things

**Comment by sbc** [comment]
I guess if the goal is to simultaneously support modal and standalone operation, probably we should just document and require a suitable local env with the right requirements installed.

Even if we get image.imports working, wouldn't that break the ability to run the code locally? (B/c the imports would be missing.)

**Comment by vshlemon** [comment]
Agreed, okay we will just have to replicate env. locally seems best - let me know how poetry install goes or if we should do a call and update the README for it at the same time

**Comment by sbc** [comment]
@vshlemon Thanks for this. It is a tremendous refactor and lays a very solid foundation for future development of the STT pipeline. I especially appreciate the work that went into decoupling the business logic from the modal code. 

The cost of this decoupling is that there are a lot of abstractions someone new to the codebase will need to wrap their head around in order to be productive. I'm finding it a bit tough to wrap my head around the call flow for the transcription job for example. We will need to invest time into documentation to mitigate some of this, and try to simplify things over time where possible.

I added a small commit to add a dir to the gitignore, but otherwise going ahead with the merge and we can continue to build on this.

I started looking at adding the transcribe button on the frontend and noticed that you added the hf key to the transcribe job, but that should be on the backend only, and not a client side or user parameter. It should come from the environment when run locally and when run in modal, passed from the modal secrets store to the environment.

**Comment by vshlemon** [comment]
Hi @sbc - thank you :) - I had some ideas to make it more obvious/well-organised as to what was happening regards call-flow - namely adding the `src` functions & types being used by the modal operators as class attributes to them (& perhaps designing a convention like "router always calls -> an operator always calls -> an ?er"). 

I also thought to make the storage stuff a class with read/write methods for each storage dir so we can check what is in there matches expectation & avoid those errors we got with blank/corrupted files etc. I think this all will take me a week as I will also try and clean up the naming conventions, remove the prints & add proper logging and exception classes etc. & then update the README.

And sure will look into adding an environment file - definitely for model settings, but _am a bit confused about storing creds there_?

Should I follow the same pattern of branching and making a PR or if it is small updates shall I push to main?

**Comment by vshlemon** [comment]
Just curious - what is the `app/frontend/src/routes` dir for?

**Comment by sbc** [comment]
> Just curious - what is the `app/frontend/src/routes` dir for?

Svelte uses the convention of organizing code under folders nested in the routes directory that correspond to the URLs themselves. So the routes directory is where the actual code for the app lives.

**Comment by sbc** [comment]
> And sure will look into adding an environment file - definitely for model settings, but am a bit confused about storing creds there?

You wouldn't be adding an environment file per se. You would be retrieving API keys using `os.env`. 

When running locally the user has the option of setting their environment variables manually or creating .env file and sourcing it into their environment or doing whatever they want to do. 

When running in modal you would use modal secrets to load the environment:

```python

import os
import modal

stub = modal.Stub()


@stub.function(secrets=[modal.Secret.from_name("secret-keys")])
def some_function():
    secret_key = os.environ["MY_PASSWORD"]
    ...

```

**Comment by vshlemon** [comment]
> > Just curious - what is the `app/frontend/src/routes` dir for?
> 
> Svelte uses the convention of organizing code under folders nested in the routes directory that correspond to the URLs themselves. So the routes directory is where the actual code for the app lives.

Ah but I thought all the svelte/ui stuff was now in the `frontend` dir, can it not be there, must it be in `app/frontend` or did this latter folder get auto-generated by an old setting perhaps

Okay think I get it on the creds, just means we have to tell anyone working with the codebase to set an envvar. I put it in the API call as I imagined a user accessing the frontend and them sending their creds over that way

**Comment by sbc** [comment]
Oh yeah not sure why app reappeared. Did that come from my commit?

**Comment by vshlemon** [comment]
Yep - no worries, I can remove it - I will move the file in there to the new folder

**Pull request merged**
