### PR TITLE
Update Frontend design and address several Backend issues

### PR DESCRIPTION
**Pull request by sbc**
Backend
- Move HuggingFace API key to Modal secrets
- Rename podcast_endpoint URL to be more RESTful
- Restore call to repopulate metadata in podcast_endpoint
- Update deprecated Modal NetworkFileSystem API
- Add image_url to podcast metadata

Frontent
- Clean up design
- Implement Svelte stores to make app more responsive
- Show placeholders while data is loading
- Add Transcribe button

Note: Transcribe button really needs the job functionality put back to work

### CODE REVIEW

**Comment by vishnu-mapaction** [comment]
Hi @sbc - I'm getting a `Not Found Error: Could not find secret` - where does modal read the secret in from?

**Comment by vshlemon** [comment]
Hi @sbc - I'm getting a Not Found Error: Could not find secret - where does modal read the secret in from?

Also it seems the branch diverged from an older version of main so there are likely to be some conflicts on merge

**Comment by vshlemon** [comment]
Figured it out via. https://modal.com/docs/guide/secrets that you need to do it on the modal dashboard, might be good to put it in the README.md - maybe we could do a call to merge everything and then start on the next steps we discussed before?

**Comment by vshlemon** [comment]
I merged but will need to make some edits to:
1. Update README.md to explain how to make secrets available to modal
2. Change secret name to 'HUGGING_FACE_ACCESS_TOKEN' to make more obvious
3. Passing the secret into the `PyannoteDiariser` call in `DiariseAndTranscribeModalOperator` so it is clearer where it is being passed in from, and also so that when you use the `PyannoteDiariser` on its own outside of modal you can init the class with the secret string rather than having to set an os.env var

**Pull request merged**
